require File.expand_path("../inpact/api",__FILE__)
require File.expand_path("../inpact/configuration",__FILE__)
require File.expand_path("../inpact/resource",__FILE__)
require File.expand_path("../inpact/account",__FILE__)
require File.expand_path("../inpact/reward",__FILE__)
require File.expand_path("../inpact/email_reward",__FILE__)
require File.expand_path("../inpact/giving_link",__FILE__)
